# Generated by Django 3.0.2 on 2020-02-15 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Exam Category Id')),
                ('exam_school_title', models.CharField(max_length=254, verbose_name='Exam Category Title')),
                ('exam_school_slug', models.SlugField(max_length=254, unique=True, verbose_name='Exam Category Slug')),
                ('exam_school_description', models.TextField(blank=True, null=True, verbose_name='Exam Category Description')),
                ('exam_school_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Exam Category Created Date')),
            ],
            options={
                'ordering': ['-exam_school_created_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Exam Sub Category Id')),
                ('exam_department_title', models.CharField(max_length=254, verbose_name='Exam Sub Category Title')),
                ('exam_department_slug', models.SlugField(max_length=254, unique=True, verbose_name='Exam Sub Category Slug')),
                ('exam_department_description', models.TextField(blank=True, null=True, verbose_name='Exam Sub Category Description')),
                ('exam_department_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Exam Sub Category Created Date')),
                ('exam_school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamSchool', verbose_name='Exam Main Category')),
            ],
            options={
                'ordering': ['-exam_department_created_date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Exam Id')),
                ('exam_title', models.CharField(max_length=254, verbose_name='Exam Title')),
                ('exam_slug', models.SlugField(max_length=254, unique=True, verbose_name='Exam Title Slug')),
                ('exam_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Exam Created Date')),
                ('exam_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Exam File')),
                ('exam_view', models.PositiveIntegerField(default=0, verbose_name='Exam View Count')),
                ('exam_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Exam Author')),
                ('exam_school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamDepartment', verbose_name='Exam Department')),
            ],
            options={
                'ordering': ['-exam_created_date'],
            },
        ),
    ]
