# Generated by Django 3.0.2 on 2020-03-31 21:44

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('view', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Exam',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False)),
                ('isSchool', models.BooleanField(default=False)),
                ('isDepartment', models.BooleanField(default=False)),
                ('isLecture', models.BooleanField(default=False)),
                ('tree', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, default=list, max_length=200, size=None)),
                ('view', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('isCategory', models.BooleanField(default=False)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.School')),
            ],
            options={
                'db_table': 'School',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('media', models.FileField(default='default-user-image.png', upload_to='')),
                ('creator', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('examId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exam.Exam')),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.ExamComment')),
            ],
            options={
                'db_table': 'ExamComment',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='lectureId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.School', verbose_name='Dersi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schoolId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.School')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountSchool',
            },
        ),
    ]
