# Generated by Django 3.0.2 on 2020-02-28 13:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_tag'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Makale Tag Id')),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='Makale')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Tag')),
            ],
            options={
                'db_table': 'ExamTag',
            },
        ),
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Yorum Id')),
                ('creator', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Yorum')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False, verbose_name='Root Durumu')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Yorum Görüntülenme Tarihi')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Yorum Beğeni Sayısı')),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='Makale Yorumcusu')),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cevap', to='exam.ExamComment')),
            ],
            options={
                'db_table': 'ExamComment',
                'ordering': ['-createdDate'],
            },
        ),
    ]
