# Generated by Django 3.0.2 on 2020-02-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='departmentId',
        ),
        migrations.AddField(
            model_name='exam',
            name='lectureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Lecture', verbose_name='Bölüm Adı'),
        ),
    ]
