# Generated by Django 3.0.2 on 2020-03-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='since',
        ),
    ]
