# Generated by Django 3.0.2 on 2020-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bölüm Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sınav Sorusu Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolUpdatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih'),
        ),
    ]
