# Generated by Django 3.0.2 on 2020-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200228_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcomment',
            name='view',
        ),
        migrations.AddField(
            model_name='department',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AddField(
            model_name='examtag',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Sınav Tag Görüntülenme Tarihi'),
        ),
        migrations.AddField(
            model_name='school',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=254, verbose_name='Dönem (Bahar-Kış-Yaz)'),
        ),
    ]
