# Generated by Django 3.0.2 on 2020-04-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200418_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcategory',
            name='isTerm',
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254),
        ),
    ]
