# Generated by Django 3.0.2 on 2020-03-07 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_school_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtag',
            name='examId',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='termId',
        ),
        migrations.RemoveField(
            model_name='term',
            name='departmentId',
        ),
        migrations.AddField(
            model_name='exam',
            name='departmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Department', verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='exam',
            name='schoolId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.School', verbose_name='Okul'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tagId',
            field=models.ManyToManyField(to='exam.ExamTag', verbose_name='Etiket'),
        ),
        migrations.AddField(
            model_name='exam',
            name='termId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Term', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='examtag',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examtag',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Aktiflik'),
        ),
        migrations.AddField(
            model_name='examtag',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Yorum Beğeni Sayısı'),
        ),
        migrations.AddField(
            model_name='examtag',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='departmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Department', verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='term',
            name='lectureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Lecture', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lectureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Lecture', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='examtag',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Yorum Görüntülenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
    ]
