# Generated by Django 3.0.2 on 2020-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200421_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcategory',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
