# Generated by Django 3.0.2 on 2020-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200307_2333'),
        ('exam', '0003_auto_20200307_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tagId',
        ),
        migrations.AddField(
            model_name='examtag',
            name='examId',
            field=models.ManyToManyField(null=True, to='exam.Exam', verbose_name='Sınav'),
        ),
        migrations.RemoveField(
            model_name='examtag',
            name='tagId',
        ),
        migrations.AddField(
            model_name='examtag',
            name='tagId',
            field=models.ManyToManyField(null=True, to='adminpanel.Tag', verbose_name='Etiket'),
        ),
    ]
