# Generated by Django 3.0.2 on 2020-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200228_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Aktiflik'),
        ),
        migrations.AddField(
            model_name='term',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
