# Generated by Django 3.0.2 on 2020-02-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200229_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='media',
        ),
        migrations.AddField(
            model_name='exam',
            name='departmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Department', verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='schoolId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.School', verbose_name='Okul Adı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='termId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Term', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='schoolId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.School', verbose_name='Okul Adı'),
        ),
        migrations.AlterField(
            model_name='department',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='school',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya'),
        ),
    ]
