# Generated by Django 3.0.2 on 2020-02-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200229_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='schoolId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.School', verbose_name='Okul Adı'),
        ),
    ]
