# Generated by Django 3.0.2 on 2020-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200308_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtag',
            name='examId',
            field=models.ManyToManyField(to='exam.Exam', verbose_name='Sınav'),
        ),
    ]
