# Generated by Django 3.0.2 on 2020-03-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_term_schoolid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='lectureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Lecture', verbose_name='Ders Adı'),
        ),
    ]
