# Generated by Django 3.0.2 on 2020-03-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200301_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='departmentId',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='schoolId',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='termId',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='departmentId',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='schoolId',
        ),
        migrations.RemoveField(
            model_name='term',
            name='schoolId',
        ),
    ]
