# Generated by Django 3.0.2 on 2020-02-25 22:08

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biyografi')),
                ('image', models.FileField(default='default-user-image.png', upload_to='', verbose_name='Profil Resmi')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Makale Görüntülenme Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Account',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Grup Id')),
                ('title', models.CharField(max_length=100, verbose_name='Grup Adı')),
                ('slug', models.CharField(max_length=254, unique=True, verbose_name='Unique Grup Adı')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Grup Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Grup Güncellendiği Tarih')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
            ],
            options={
                'db_table': 'Group',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='İzin Id')),
                ('title', models.CharField(max_length=100, verbose_name='İzin Adı')),
                ('slug', models.CharField(max_length=254, unique=True, verbose_name='Unique İzin Adı')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='İzin Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='İzin Güncellendiği Tarih')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
            ],
            options={
                'db_table': 'Permission',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Account Group Permission Id')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Grup İzni Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Grup İzni Güncellendiği Tarih')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Group', verbose_name='Grup Adı')),
                ('permissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Permission', verbose_name='İzin Adı')),
            ],
            options={
                'db_table': 'GroupPermission',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='AccountPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Hesap İzin Id')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Hesap İzni Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Hesap İzni Güncellendiği Tarih')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
                ('permissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Permission', verbose_name='Bağlı Olduğu İzin')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bağlı Olduğu Hesap')),
            ],
            options={
                'db_table': 'AccountPermission',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Account Group Id')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Hesap Grup Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Hesap Grup Oluşturulduğu Tarih')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Group', verbose_name='Grup Adı')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'db_table': 'AccountGroup',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Aktivite Id')),
                ('activityTitle', models.CharField(max_length=254, verbose_name='Başlık')),
                ('activityApplication', models.CharField(max_length=254, verbose_name='Uygulama')),
                ('activityDescription', models.CharField(max_length=254, verbose_name='Açıklama')),
                ('activityMethod', models.CharField(max_length=254, verbose_name='Method Türü')),
                ('activityCreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('activityUpdatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih')),
                ('activityCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kişi')),
            ],
            options={
                'db_table': 'AccountActivity',
                'ordering': ['-activityCreatedDate'],
            },
        ),
    ]
