# Generated by Django 3.0.2 on 2020-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hesap Grup Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hesap İzni Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityUpdatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grup Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grup İzni Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İzin Güncellendiği Tarih'),
        ),
    ]
