# Generated by Django 3.0.2 on 2020-03-04 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Sosyal Medya Id')),
                ('title', models.CharField(max_length=254, verbose_name='Sosyal Medya Adı')),
                ('slug', models.SlugField(verbose_name='Sosyal Medya Adı Slug')),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktiflik')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih')),
            ],
            options={
                'db_table': 'SocialMedia',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.RemoveField(
            model_name='accountactivity',
            name='activityUpdatedDate',
        ),
        migrations.CreateModel(
            name='AccountSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Account Social Media Id')),
                ('url', models.URLField(verbose_name='Sosyal Medya URL')),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Görünürlük')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih')),
                ('socialMediaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.SocialMedia', verbose_name='Sosyal Medya Adı')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'db_table': 'AccountSocialMedia',
                'ordering': ['-createdDate'],
            },
        ),
    ]
