# Generated by Django 3.0.2 on 2020-02-26 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='groupTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Group Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Kullanıcı Adı'),
            preserve_default=False,
        ),
    ]
