# Generated by Django 3.0.2 on 2020-03-31 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivity',
            name='slug',
        ),
    ]
