# Generated by Django 3.0.2 on 2020-02-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maingroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Grup Adı'),
        ),
        migrations.AlterField(
            model_name='maingroup',
            name='name_slug',
            field=models.CharField(max_length=254, unique=True, verbose_name='Unique Grup Adı'),
        ),
    ]
