# Generated by Django 3.0.2 on 2020-03-21 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountactivity',
            options={'ordering': ['-createdDate']},
        ),
        migrations.RenameField(
            model_name='accountactivity',
            old_name='activityApplication',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='accountactivity',
            old_name='activityCreatedDate',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='accountactivity',
            old_name='activityCreator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='accountactivity',
            old_name='activityDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='accountactivity',
            old_name='activityMethod',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='accountactivity',
            old_name='activityTitle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='accountactivity',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
