# Generated by Django 3.0.2 on 2020-02-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200220_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maingroup',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='mainpermission',
            name='description',
        ),
    ]
