# Generated by Django 3.0.2 on 2020-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200304_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Sosyal Medya Adı Slug'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(max_length=254, unique=True, verbose_name='Sosyal Medya Adı'),
        ),
    ]
