# Generated by Django 3.0.2 on 2020-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_accountactivity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
