# Generated by Django 3.0.2 on 2020-03-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200321_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivity',
            name='slug',
        ),
    ]
