# Generated by Django 3.0.2 on 2020-02-26 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200226_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpermission',
            name='permissionTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='İzin Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountpermission',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Kullanıcı Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='groupTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Group Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='permissionTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='İzin Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='activityCreator',
            field=models.CharField(max_length=254, verbose_name='Oluşturan Kişi'),
        ),
    ]
