# Generated by Django 3.0.2 on 2020-04-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_permission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpermission',
            name='groupId',
        ),
        migrations.AddField(
            model_name='accountpermission',
            name='permissionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Permission'),
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
    ]
