# Generated by Django 3.0.2 on 2020-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200226_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroup',
            name='groupTitle',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='username',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='groupTitle',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='permissionTitle',
        ),
    ]
