# Generated by Django 3.0.2 on 2020-03-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200307_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug'),
        ),
    ]
