# Generated by Django 3.0.2 on 2020-03-21 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_accountactivity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivity',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='media',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
