# Generated by Django 3.0.2 on 2020-04-09 17:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200408_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cv',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
