# Generated by Django 3.0.2 on 2020-02-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200226_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpermission',
            name='permissionTitle',
        ),
        migrations.RemoveField(
            model_name='accountpermission',
            name='username',
        ),
    ]
