# Generated by Django 3.0.2 on 2020-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200322_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Admin?'),
        ),
    ]
