# Generated by Django 3.0.2 on 2020-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsocialmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
