# Generated by Django 3.0.2 on 2020-02-26 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200226_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hesap Güncellendiği Tarih'),
            preserve_default=False,
        ),
    ]
