# Generated by Django 3.0.2 on 2020-04-09 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200409_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(db_table='AccountFollowing', default=0, related_name='_account_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
