# Generated by Django 3.0.2 on 2020-04-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='AccountFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerId', to=settings.AUTH_USER_MODEL)),
                ('followingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountFollow',
            },
        ),
    ]
