# Generated by Django 3.0.2 on 2020-04-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200409_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountActivity',
            new_name='AccountLogs',
        ),
        migrations.AlterModelTable(
            name='accountlogs',
            table='AccountLogs',
        ),
    ]
