# Generated by Django 3.0.2 on 2020-04-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200413_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
