# Generated by Django 3.0.2 on 2020-04-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_socialmedia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='media',
        ),
    ]
