# Generated by Django 3.0.2 on 2020-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_socialmedia_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['slug']},
        ),
    ]
