# Generated by Django 3.0.2 on 2020-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200413_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='socialMediaUsername',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
