# Generated by Django 3.0.2 on 2020-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_socialmedia_socialmediausername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='socialMediaUsername',
        ),
        migrations.AddField(
            model_name='accountsocialmedia',
            name='socialMediaUsername',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
