# Generated by Django 3.0.2 on 2020-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200413_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='graduate',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
