# Generated by Django 3.0.2 on 2020-04-13 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_graduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='groupId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Group'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
