# Generated by Django 3.0.2 on 2020-04-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200414_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogs',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='permissionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Permission'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountsocialmedia',
            name='socialMediaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SocialMedia'),
        ),
        migrations.AlterField(
            model_name='accountsocialmedia',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountzones',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountzones',
            name='zoneId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Zones'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='parentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Zones'),
        ),
    ]
