# Generated by Django 3.0.2 on 2020-04-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200415_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountZones',
            new_name='AccountZone',
        ),
        migrations.RenameModel(
            old_name='Zones',
            new_name='Zone',
        ),
        migrations.AlterModelTable(
            name='accountzone',
            table='AccountZone',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='Zone',
        ),
    ]
