# Generated by Django 3.0.2 on 2020-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_accountskill_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='method',
        ),
        migrations.AddField(
            model_name='notification',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
