# Generated by Django 3.0.2 on 2020-02-15 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Course Category Id')),
                ('course_category_title', models.CharField(max_length=254, verbose_name='Course Category Title')),
                ('course_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Course Category Slug')),
                ('course_category_description', models.TextField(blank=True, null=True, verbose_name='Course Category Description')),
                ('course_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Course Category Created Date')),
            ],
            options={
                'ordering': ['-course_category_created_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Course Sub Category Id')),
                ('course_sub_category_title', models.CharField(max_length=254, verbose_name='Course Sub Category Title')),
                ('course_sub_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Course Sub Category Slug')),
                ('course_sub_category_description', models.TextField(blank=True, null=True, verbose_name='Course Sub Category Description')),
                ('course_sub_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Course Sub Category Created Date')),
                ('course_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseCategory', verbose_name='Course Main Category')),
            ],
            options={
                'ordering': ['-course_sub_category_created_date'],
            },
        ),
    ]
