# Generated by Django 3.0.2 on 2020-02-16 15:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs Kategori Id')),
                ('course_category_title', models.CharField(max_length=254, verbose_name='Kurs Kategori Başlığı')),
                ('course_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Kurs Kategori Slug')),
                ('course_category_description', models.TextField(blank=True, null=True, verbose_name='Kurs Kategori Açıklama')),
                ('course_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Kurs Kategori Oluşturulduğu Tarih')),
                ('course_category_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kişi')),
            ],
            options={
                'ordering': ['-course_category_created_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs Alt Kategori Id')),
                ('course_sub_category_title', models.CharField(max_length=254, verbose_name='Kurs Alt Kategori Başlığı')),
                ('course_sub_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Kurs Alt Kategori Slug')),
                ('course_sub_category_description', models.TextField(blank=True, null=True, verbose_name='Kurs Alt Kategori Açıklama')),
                ('course_sub_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Kurs Alt Kategori Oluşturulduğu Tarih')),
                ('course_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseCategory', verbose_name='Kurs Ana Kategori')),
                ('course_sub_category_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kişi')),
            ],
            options={
                'ordering': ['-course_sub_category_created_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubToSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs En Alt Kategori Id')),
                ('course_sub_to_sub_category_title', models.CharField(max_length=254, verbose_name='Kurs En Alt Kategori Başlığı')),
                ('course_sub_to_sub_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Kurs En Alt Kategori Slug')),
                ('course_sub_to_sub_category_description', models.TextField(blank=True, null=True, verbose_name='Kurs En Alt Kategori Açıklama')),
                ('course_sub_to_sub_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Kurs En Alt Kategori Oluşturulduğu Tarih')),
                ('course_sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseSubCategory', verbose_name='Kurs Alt Kategori')),
                ('course_sub_to_sub_category_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kişi')),
            ],
            options={
                'ordering': ['-course_sub_to_sub_category_created_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs Id')),
                ('course_title', models.CharField(max_length=254, verbose_name='Kurs Başlığı')),
                ('course_slug', models.SlugField(max_length=254, unique=True, verbose_name='Kurs Slug')),
                ('course_content', ckeditor.fields.RichTextField(verbose_name='Kurs Açıklaması')),
                ('course_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Kurs Dosya Yükleme')),
                ('course_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Kurs Oluşturulduğu Tarih')),
                ('course_view', models.PositiveIntegerField(default=0, verbose_name='Kurs Görüntülenme Tarihi')),
                ('course_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kurs Öğretmeni')),
                ('course_sub_to_sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseSubToSubCategory', verbose_name='Kurs En Alt Kategori')),
            ],
            options={
                'ordering': ['-course_created_date'],
            },
        ),
    ]
