# Generated by Django 3.0.2 on 2020-03-07 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetag',
            name='courseId',
        ),
        migrations.AddField(
            model_name='course',
            name='tagId',
            field=models.ManyToManyField(to='course.CourseTag', verbose_name='Etiket'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetag',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Aktiflik'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Yorum Beğeni Sayısı'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Yorum Görüntülenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
    ]
