# Generated by Django 3.0.2 on 2020-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kurs Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kurs Kategori Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='courselecture',
            name='updatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ders Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='updatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kurs Bölüm Düzenlendiği Tarih'),
        ),
    ]
