# Generated by Django 3.0.2 on 2020-05-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='catNumber',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
