# Generated by Django 3.0.2 on 2020-02-27 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kurs Kategori Açıklama'),
        ),
    ]
