# Generated by Django 3.0.2 on 2020-02-16 11:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubToSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Makale Alt Kategori Id')),
                ('course_sub_to_sub_category_title', models.CharField(max_length=254, verbose_name='Makale Alt Kategori Başlığı')),
                ('course_sub_to_sub_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Makale Alt Kategori Slug')),
                ('course_sub_to_sub_category_description', models.TextField(blank=True, null=True, verbose_name='Makale Alt Kategori Açıklama')),
                ('course_sub_to_sub_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Makale Alt Kategori Oluşturulduğu Tarih')),
                ('course_sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseSubCategory', verbose_name='Alt Kategori')),
            ],
            options={
                'ordering': ['-course_sub_to_sub_category_created_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs Id')),
                ('course_title', models.CharField(max_length=254, verbose_name='Course Title')),
                ('course_slug', models.SlugField(max_length=254, unique=True, verbose_name='Course Slug')),
                ('course_content', ckeditor.fields.RichTextField(verbose_name='Course Description')),
                ('course_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Course File')),
                ('course_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Course Created Date')),
                ('course_view', models.PositiveIntegerField(default=0, verbose_name='Course View Count')),
                ('course_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Course Author')),
                ('course_sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseSubCategory', verbose_name='Course Sub Category')),
            ],
            options={
                'ordering': ['-course_created_date'],
            },
        ),
    ]
