# Generated by Django 3.0.2 on 2020-04-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='isCategory',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
