# Generated by Django 3.0.2 on 2020-05-25 20:55

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursecategory_catnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='introduction',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
