# Generated by Django 3.0.2 on 2020-04-14 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_coursecategory_iscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='isCategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.CourseCategory'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
