# Generated by Django 3.0.2 on 2020-05-04 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200415_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
