# Generated by Django 3.0.2 on 2020-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200307_2333'),
        ('course', '0002_auto_20200307_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tagId',
        ),
        migrations.AddField(
            model_name='coursetag',
            name='courseId',
            field=models.ManyToManyField(null=True, to='course.Course', verbose_name='Kurs'),
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='tagId',
        ),
        migrations.AddField(
            model_name='coursetag',
            name='tagId',
            field=models.ManyToManyField(null=True, to='adminpanel.Tag', verbose_name='Etiket'),
        ),
    ]
