# Generated by Django 3.0.2 on 2020-04-14 01:29

import ankadescankaya.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200414_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursePicture',
            field=models.FileField(blank=True, default='no-image-available.png', null=True, storage=ankadescankaya.storage_backends.CourseMediaStorage(), upload_to=''),
        ),
    ]
