# Generated by Django 3.0.2 on 2020-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200308_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='courseId',
            field=models.ManyToManyField(to='course.Course', verbose_name='Kurs'),
        ),
    ]
