# Generated by Django 3.0.2 on 2020-05-25 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200526_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
