# Generated by Django 3.0.2 on 2020-05-25 22:52

import ankadescankaya.storage_backends
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200526_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='media',
            field=models.FileField(default=django.utils.timezone.now, storage=ankadescankaya.storage_backends.CourseMediaStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
