# Generated by Django 3.0.2 on 2020-05-25 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursevideo_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='sectionNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
