# Generated by Django 3.0.2 on 2020-05-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_coursesection_sectionnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='title',
        ),
    ]
