# Generated by Django 3.0.2 on 2020-05-26 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_auto_20200526_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, db_table='AccountCourseLiked', default=0, related_name='courseLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
