# Generated by Django 3.0.2 on 2020-02-28 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs Id')),
                ('activityCreator', models.CharField(max_length=254, verbose_name='Oluşturan Kişi')),
                ('activityTitle', models.CharField(max_length=254, verbose_name='Başlık')),
                ('activityApplication', models.CharField(max_length=254, verbose_name='Uygulama')),
                ('activityDescription', models.CharField(max_length=254, verbose_name='Açıklama')),
                ('activityMethod', models.CharField(max_length=254, verbose_name='Method Türü')),
                ('activityCreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('activityUpdatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih')),
            ],
            options={
                'db_table': 'AdminActivity',
                'ordering': ['-activityCreatedDate'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Tag Id')),
                ('title', models.CharField(max_length=254, unique=True, verbose_name='Tag Adı')),
                ('slug', models.SlugField(max_length=254, verbose_name='Slug')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Tag Görüntülenme')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktiflik')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kişi')),
            ],
            options={
                'db_table': 'Tag',
                'ordering': ['-createdDate'],
            },
        ),
    ]
