# Generated by Django 3.0.2 on 2020-03-31 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254)),
                ('view', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tag',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('application', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('method', models.CharField(max_length=254)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AdminActivity',
                'ordering': ['-createdDate'],
            },
        ),
    ]
