# Generated by Django 3.0.2 on 2020-02-25 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Kurs Id')),
                ('activityTitle', models.CharField(max_length=254, verbose_name='Başlık')),
                ('activityApplication', models.CharField(max_length=254, verbose_name='Uygulama')),
                ('activityDescription', models.CharField(max_length=254, verbose_name='Açıklama')),
                ('activityMethod', models.CharField(max_length=254, verbose_name='Method Türü')),
                ('activityCreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('activityUpdatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih')),
                ('activityCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kişi')),
            ],
            options={
                'db_table': 'AdminActivity',
                'ordering': ['-activityCreatedDate'],
            },
        ),
    ]
