# Generated by Django 3.0.2 on 2020-03-07 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactivity',
            options={'ordering': ['-createdDate']},
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityApplication',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityCreatedDate',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityCreator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityMethod',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='activityUpdatedDate',
            new_name='updatedDate',
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, verbose_name='Slug'),
        ),
    ]
