# Generated by Django 3.0.2 on 2020-03-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactivity',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='adminactivity',
            name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updatedDate',
        ),
    ]
