# Generated by Django 3.0.2 on 2020-03-07 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20200307_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
