# Generated by Django 3.0.2 on 2020-03-07 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20200307_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Güncellendiği Tarih'),
            preserve_default=False,
        ),
    ]
