# Generated by Django 3.0.2 on 2020-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_tag_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih'),
        ),
    ]
