# Generated by Django 3.0.2 on 2020-04-25 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0005_sitesettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='isRead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='isSolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
