# Generated by Django 3.0.2 on 2020-04-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20200426_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
