# Generated by Django 3.0.2 on 2020-02-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Makale Kategori Id')),
                ('article_category_title', models.CharField(max_length=254, verbose_name='Makale Kategori Başlığı')),
                ('article_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Makale Kategori Slug')),
                ('article_category_description', models.TextField(blank=True, null=True, verbose_name='Makale Kategori Açıklama')),
                ('article_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Makale Kategori Oluşturulma Tarihi')),
                ('article_category_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Makale Kategori Başlığı')),
            ],
            options={
                'ordering': ['-article_category_created_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Makale Alt Kategori Id')),
                ('article_sub_category_title', models.CharField(max_length=254, verbose_name='Makale Alt Kategori Başlık')),
                ('article_sub_category_slug', models.SlugField(max_length=254, unique=True, verbose_name='Makale Alt Kategori Slug')),
                ('article_sub_category_description', models.TextField(blank=True, null=True, verbose_name='Makale Alt Kategori Açıklama')),
                ('article_sub_category_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Makale Oluşturulma Tarihi')),
                ('article_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory', verbose_name='Makale Ana Kategori')),
                ('article_sub_category_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Makale Yazarı')),
            ],
            options={
                'ordering': ['-article_sub_category_created_date'],
            },
        ),
    ]
