# Generated by Django 3.0.2 on 2020-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='isCategory',
            field=models.BooleanField(default=False, verbose_name='Üst Kategori mi?'),
        ),
    ]
