# Generated by Django 3.0.2 on 2020-04-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
