# Generated by Django 3.0.2 on 2020-03-04 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecategory_iscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletag',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Aktiflik'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Yorum Beğeni Sayısı'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articletag',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Yorum Görüntülenme Tarihi'),
        ),
    ]
