# Generated by Django 3.0.2 on 2020-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200512_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
