# Generated by Django 3.0.2 on 2020-02-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200227_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Özellik'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Makale Yorumcusu'),
        ),
    ]
