# Generated by Django 3.0.2 on 2020-04-13 18:31

import ankadescankaya.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.FileField(blank=True, default='no-image-available.png', null=True, storage=ankadescankaya.storage_backends.ArticleMediaStorage(), upload_to=''),
        ),
    ]
