# Generated by Django 3.0.2 on 2020-03-07 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20200304_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='articleId',
        ),
        migrations.AddField(
            model_name='article',
            name='tagId',
            field=models.ManyToManyField(to='article.ArticleTag', verbose_name='Etiket'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Makale Oluşturan'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=254, unique=True, verbose_name='Slug'),
        ),
    ]
