# Generated by Django 3.0.2 on 2020-02-28 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_tag'),
        ('article', '0003_auto_20200227_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Makale Tag Id')),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Makale')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Tag')),
            ],
            options={
                'db_table': 'ArticleTag',
            },
        ),
    ]
