# Generated by Django 3.0.2 on 2020-04-23 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200415_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='commentNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
