# Generated by Django 3.0.2 on 2020-05-19 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
