# Generated by Django 3.0.2 on 2020-03-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200307_2333'),
        ('article', '0004_auto_20200307_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tagId',
        ),
        migrations.AddField(
            model_name='articletag',
            name='articleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Article', verbose_name='Kullanıcı Adı'),
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='tagId',
        ),
        migrations.AddField(
            model_name='articletag',
            name='tagId',
            field=models.ManyToManyField(null=True, to='adminpanel.Tag', verbose_name='Etiket'),
        ),
    ]
