# Generated by Django 3.0.2 on 2020-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlecomment_commentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='isReply',
            field=models.BooleanField(default=False),
        ),
    ]
