# Generated by Django 3.0.2 on 2020-05-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlecategory_catnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='catNumber',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
