# Generated by Django 3.0.2 on 2020-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Makale Güncellendiği Tarih'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Makale Kategori Güncellendiği Tarih'),
        ),
    ]
