# Generated by Django 3.0.2 on 2020-03-31 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncomment',
            name='like',
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='likes',
            field=models.ManyToManyField(blank=True, db_table='LikedQuestionComment', default=0, related_name='questionCommentLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, db_table='LikedQuestion', default=0, related_name='questionLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
