# Generated by Django 3.0.2 on 2020-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200512_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='catNumber',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
