# Generated by Django 3.0.2 on 2020-04-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200401_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='isPrivate',
        ),
    ]
