# Generated by Django 3.0.2 on 2020-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200307_2333'),
        ('question', '0002_auto_20200307_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tagId',
        ),
        migrations.AddField(
            model_name='questiontag',
            name='questionId',
            field=models.ManyToManyField(null=True, to='question.Question', verbose_name='Soru'),
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='tagId',
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tagId',
            field=models.ManyToManyField(null=True, to='adminpanel.Tag', verbose_name='Etiket'),
        ),
    ]
