# Generated by Django 3.0.2 on 2020-04-01 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_question_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='answerNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='isCertified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='isRoot',
            field=models.BooleanField(default=True),
        ),
    ]
