# Generated by Django 3.0.2 on 2020-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200401_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='isReply',
            field=models.BooleanField(default=True),
        ),
    ]
