# Generated by Django 3.0.2 on 2020-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_questioncomment_isreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='isReply',
            field=models.BooleanField(default=False),
        ),
    ]
