# Generated by Django 3.0.2 on 2020-03-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200307_2333'),
        ('question', '0005_auto_20200308_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontag',
            name='questionId',
        ),
        migrations.AddField(
            model_name='questiontag',
            name='questionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Question', verbose_name='Soru'),
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='tagId',
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tagId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.Tag', verbose_name='Etiket'),
        ),
    ]
