# Generated by Django 3.0.2 on 2020-04-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200401_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='introduction',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
