# Generated by Django 3.0.2 on 2020-04-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0009_auto_20200413_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionCategory'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionCommentId', to='question.QuestionComment'),
        ),
    ]
