# Generated by Django 3.0.2 on 2020-04-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200415_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='vote',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
