# Generated by Django 3.0.2 on 2020-04-17 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0011_questioncomment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncomment',
            name='view',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='vote',
        ),
        migrations.AddField(
            model_name='question',
            name='isSolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='votes',
            field=models.ManyToManyField(blank=True, db_table='VotedAnswers', default=0, related_name='questionCommentVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
