# Generated by Django 3.0.2 on 2020-04-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20200418_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionNumber',
            new_name='postNumber',
        ),
    ]
