# Generated by Django 3.0.2 on 2020-05-08 13:15

import ankadescankaya.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isCategory', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Support')),
            ],
            options={
                'db_table': 'Support',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('displayMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('supportNumber', models.CharField(max_length=32, unique=True)),
                ('post', models.CharField(max_length=32, verbose_name='Application Post Number')),
                ('description', models.CharField(max_length=254)),
                ('isActive', models.BooleanField(default=True)),
                ('isRead', models.BooleanField(default=True)),
                ('isSolved', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(blank=True, null=True, storage=ankadescankaya.storage_backends.SupportMediaStorage(), upload_to='')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Support')),
            ],
            options={
                'db_table': 'Report',
                'ordering': ['-createdDate'],
            },
        ),
    ]
