# Generated by Django 3.0.2 on 2020-04-25 23:23

import ankadescankaya.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('displayMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('supportNumber', models.CharField(max_length=32, unique=True)),
                ('post', models.CharField(max_length=32, verbose_name='Application Post Number')),
                ('description', models.CharField(max_length=254)),
                ('isActive', models.BooleanField(default=True)),
                ('isRead', models.BooleanField(default=True)),
                ('isSolved', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(blank=True, null=True, storage=ankadescankaya.storage_backends.SupportMediaStorage(), upload_to='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Report',
                'ordering': ['-createdDate'],
            },
        ),
    ]
