# Generated by Django 3.0.2 on 2020-05-08 15:52

import ankadescankaya.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='post',
            new_name='postNumber',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='supportNumber',
            new_name='reportNumber',
        ),
        migrations.RemoveField(
            model_name='report',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='report',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='support',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='support',
            name='isCategory',
        ),
        migrations.RemoveField(
            model_name='support',
            name='isRoot',
        ),
        migrations.RemoveField(
            model_name='support',
            name='parentId',
        ),
        migrations.RemoveField(
            model_name='support',
            name='slug',
        ),
        migrations.AddField(
            model_name='report',
            name='creatorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportCreatorId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='ownerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportOwnerId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='creatorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatorId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='displayMessage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='isRead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='support',
            name='isSolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='support',
            name='media',
            field=models.FileField(blank=True, null=True, storage=ankadescankaya.storage_backends.SupportMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='support',
            name='ownerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownerId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='postNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='Application Post Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='supportNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='support',
            name='updatedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupportSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isCategory', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.SupportSubject')),
            ],
            options={
                'db_table': 'SupportSubject',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isCategory', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.ReportSubject')),
            ],
            options={
                'db_table': 'ReportSubject',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='subjectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportSubjectId', to='support.ReportSubject'),
        ),
        migrations.AddField(
            model_name='support',
            name='subjectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectId', to='support.SupportSubject'),
        ),
    ]
