# Generated by Django 3.0.2 on 2020-04-26 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_auto_20200426_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('isRoot', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isCategory', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Support')),
            ],
            options={
                'db_table': 'Support',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Support'),
        ),
    ]
