# Generated by Django 3.0.2 on 2020-03-15 22:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('messageNumber', models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='Mesaj Numarası')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('message', ckeditor.fields.RichTextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(verbose_name='Son Güncelleme')),
                ('isBlocked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Engelli')),
                ('isRoot', models.BooleanField(blank=True, default=False, null=True)),
                ('isRead', models.BooleanField(blank=True, default=False, null=True, verbose_name='Okunma')),
                ('isReply', models.BooleanField(default=False, verbose_name='Yanıt mı?')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Silinen')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('likes', models.ManyToManyField(blank=True, default=0, related_name='LikedMessages', to=settings.AUTH_USER_MODEL)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directmessage.DirectMessage', verbose_name='Ebevynlik')),
            ],
            options={
                'db_table': 'DirectMessage',
                'ordering': ['-createdDate'],
            },
        ),
    ]
