# Generated by Django 3.0.2 on 2020-03-18 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageNumber', models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='Mesaj Numarası')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
            ],
            options={
                'db_table': 'Messages',
                'ordering': ['-messageNumber'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('isBlocked', models.BooleanField(blank=True, default=False, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('messageId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directmessage.Messages')),
                ('users', models.ManyToManyField(db_table='AccountGroupMessage', related_name='AccountGroupMessage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupMessages',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isBlocked', models.BooleanField(blank=True, default=False, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('messageId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directmessage.Messages')),
                ('users', models.ManyToManyField(db_table='AccountDirectMessage', related_name='AccountDirectMessage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DirectMessages',
                'ordering': ['-createdDate'],
            },
        ),
    ]
