# Generated by Django 3.0.2 on 2020-04-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessages',
            name='messageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directmessage.Messages'),
        ),
        migrations.AlterField(
            model_name='groupmessages',
            name='messageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directmessage.Messages'),
        ),
    ]
