# Generated by Django 3.0.2 on 2020-03-15 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessage', '0002_auto_20200316_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='creator',
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Kişi'),
        ),
    ]
